version: 0.0
os: linux
files:
  - source: s3://s3-bucket-kt/hello-world
    destination: /home/ec2-user/hello-world
    permissions: '755'
    owner: ec2-user
    group: ec2-user
    type: directory
    overwrite: true
  - source: test
    destination: /home/ec2-user/hello-world
